### ISSUE TITLE
Using postgis 2.2? 

### ISSUE THREAD

**Issue by rumicuna** [F4-Group/docker-postgres-postgis-sfcgal#1]
We hope you will have some insight. We would like to be able to use all the new sfcgal functions in postgis 2.2 (ie. ST_3dIntersection, ST_MakeSolid, etc.).
We tried creating new images by modifying your Docker file to use postgis 2.2 by changing the following line from:
   ENV POSTGIS http://download.osgeo.org/postgis/source/postgis-$POSTGIS_VERSION.tar.gz
to
   ENV POSTGIS http://postgis.net/stuff/postgis-2.2.0dev.tar.gz
But even though it seems to build fine, sfcgal support is not there any more.
We also tried with newer versions of geos, sfcgal, postgres (9.5) etc. but no luck.
Any ideas on how to get your image working with postgis 2.2 and SFCGAL?
I created a fork with our modifications to your Dockerfile, you can see it here:
   https://github.com/rumicuna/docker-postgres-postgis-sfcgal/tree/postgis2.2
The new docker file is here:
   https://github.com/rumicuna/docker-postgres-postgis-sfcgal/blob/postgis2.2/Dockerfile

**Comment by rumicuna** [comment]
Forgot to thank you for you amazing contribution, if it wasn't for your docker image we would be nowhere close to getting this working.

**Comment by rumicuna** [comment]
ok, made some progress, after running docker logs on the image I see that the last script (postgis-template.sh) did not run properly:
   /docker-entrypoint-initdb.d/postgis-template.sh: line 15: /usr/share/postgresql/9.4/contrib/postgis-2.2/topology.sql: No such file or directory
I ssh'd into the image and there is no  /usr/share/postgresql/9.4/contrib directory :(
Will have to find out why this directory does not exist (who is responsible for creating it and why it wasn't installed for postgis 2.2)

**Comment by rumicuna** [comment]
Also, there is no file: /usr/share/postgresql/9.4/extension/sfcgal.control

**Comment by rumicuna** [comment]
Figured it out. The only file that was missing was topology.sql. It was missing because postgis 2.2 saves it to a different location (contrib/postgis_topology-2.2 instead of contrib/postgis-2.2). The change below in the script fixed it:

POSTGIS_TOPOLOGY_CONFIG=/usr/share/postgresql/$PG_MAJOR/contrib/postgis_topology-$POSTGIS_MAJOR
gosu postgres postgres --single -j template_postgis < $POSTGIS_TOPOLOGY_CONFIG/topology.sql

**Comment by Cactusbone** [comment]
thanks for the search :) I'll use it when updating :)
If i remember correctly, sfcgal is now packaged as a proper postgresql extension, so it should be possible to install it cleanly without messing with sql files directly.

I was waiting for postgis 2.2 to be released to try to update :) not sure when i'll have time though.

anyway, thanks for the feedback ! :+1:
