### ISSUE TITLE
Pulling doesn't reach completion

### ISSUE THREAD

**Issue by cbertelli** [F4-Group/docker-postgres-postgis-sfcgal#4]
May be some configuration on my side, but it stops reaching 37.22 MB after chunk c649a7190152.

**Comment by Cactusbone** [comment]
we're using docker hub, so there's nothing we can do about that problem :(

**Comment by cbertelli** [comment]
Hello,
thanks, yesterday I tried again and it worked.
c

On Mon, Feb 29, 2016 at 6:53 PM, Charly Koza notifications@github.com
wrote:

> we're using docker hub, so there's nothing we can do about that problem :(
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/F4-Group/docker-postgres-postgis-sfcgal/issues/4#issuecomment-190309357
> .

## 

---

Carlo A. Bertelli
   Charta servizi e sistemi per il territorio e la storia ambientale srl
          Dipendenze del palazzo Doria,
          vc. alla Chiesa della Maddalena 9/2 16124      Genova (Italy)
          tel./fax +39(0)10 2475439  +39 0108566195  gsm:+39 393 1590711

##    e-mail: bertelli@chartasrl.eu      http://www.chartasrl.eu
